/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as AuthedRouteRouteImport } from "./routes/_authed/route"
import { Route as DesignRouteImport } from "./routes/design"
import { Route as LoginRouteImport } from "./routes/login"
import { Route as AuthedWorkspaceSlugRouteRouteImport } from "./routes/_authed/$workspaceSlug/route"
import { Route as AuthedOnboardingRouteImport } from "./routes/_authed/onboarding"
import { Route as AuthedBotBotIdRouteImport } from "./routes/_authed/bot/$botId"
import { Route as AuthedWorkspaceSlugBotBotIdRouteImport } from "./routes/_authed/$workspaceSlug/bot/$botId"
import { Route as AuthedWorkspaceSlugRoomRoomIdRouteImport } from "./routes/_authed/$workspaceSlug/room/$roomId"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: "/_authed",
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: "/design",
  path: "/design",
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedWorkspaceSlugRouteRoute =
  AuthedWorkspaceSlugRouteRouteImport.update({
    id: "/$workspaceSlug",
    path: "/$workspaceSlug",
    getParentRoute: () => AuthedRouteRoute,
  } as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: "/onboarding",
  path: "/onboarding",
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedBotBotIdRoute = AuthedBotBotIdRouteImport.update({
  id: "/bot/$botId",
  path: "/bot/$botId",
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedWorkspaceSlugBotBotIdRoute =
  AuthedWorkspaceSlugBotBotIdRouteImport.update({
    id: "/bot/$botId",
    path: "/bot/$botId",
    getParentRoute: () => AuthedWorkspaceSlugRouteRoute,
  } as any)
const AuthedWorkspaceSlugRoomRoomIdRoute =
  AuthedWorkspaceSlugRoomRoomIdRouteImport.update({
    id: "/room/$roomId",
    path: "/room/$roomId",
    getParentRoute: () => AuthedWorkspaceSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/design": typeof DesignRoute
  "/login": typeof LoginRoute
  "/$workspaceSlug": typeof AuthedWorkspaceSlugRouteRouteWithChildren
  "/onboarding": typeof AuthedOnboardingRoute
  "/bot/$botId": typeof AuthedBotBotIdRoute
  "/$workspaceSlug/bot/$botId": typeof AuthedWorkspaceSlugBotBotIdRoute
  "/$workspaceSlug/room/$roomId": typeof AuthedWorkspaceSlugRoomRoomIdRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/design": typeof DesignRoute
  "/login": typeof LoginRoute
  "/$workspaceSlug": typeof AuthedWorkspaceSlugRouteRouteWithChildren
  "/onboarding": typeof AuthedOnboardingRoute
  "/bot/$botId": typeof AuthedBotBotIdRoute
  "/$workspaceSlug/bot/$botId": typeof AuthedWorkspaceSlugBotBotIdRoute
  "/$workspaceSlug/room/$roomId": typeof AuthedWorkspaceSlugRoomRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/_authed": typeof AuthedRouteRouteWithChildren
  "/design": typeof DesignRoute
  "/login": typeof LoginRoute
  "/_authed/$workspaceSlug": typeof AuthedWorkspaceSlugRouteRouteWithChildren
  "/_authed/onboarding": typeof AuthedOnboardingRoute
  "/_authed/bot/$botId": typeof AuthedBotBotIdRoute
  "/_authed/$workspaceSlug/bot/$botId": typeof AuthedWorkspaceSlugBotBotIdRoute
  "/_authed/$workspaceSlug/room/$roomId": typeof AuthedWorkspaceSlugRoomRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/design"
    | "/login"
    | "/$workspaceSlug"
    | "/onboarding"
    | "/bot/$botId"
    | "/$workspaceSlug/bot/$botId"
    | "/$workspaceSlug/room/$roomId"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/design"
    | "/login"
    | "/$workspaceSlug"
    | "/onboarding"
    | "/bot/$botId"
    | "/$workspaceSlug/bot/$botId"
    | "/$workspaceSlug/room/$roomId"
  id:
    | "__root__"
    | "/"
    | "/_authed"
    | "/design"
    | "/login"
    | "/_authed/$workspaceSlug"
    | "/_authed/onboarding"
    | "/_authed/bot/$botId"
    | "/_authed/$workspaceSlug/bot/$botId"
    | "/_authed/$workspaceSlug/room/$roomId"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  DesignRoute: typeof DesignRoute
  LoginRoute: typeof LoginRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed": {
      id: "/_authed"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/design": {
      id: "/design"
      path: "/design"
      fullPath: "/design"
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_authed/$workspaceSlug": {
      id: "/_authed/$workspaceSlug"
      path: "/$workspaceSlug"
      fullPath: "/$workspaceSlug"
      preLoaderRoute: typeof AuthedWorkspaceSlugRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    "/_authed/onboarding": {
      id: "/_authed/onboarding"
      path: "/onboarding"
      fullPath: "/onboarding"
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    "/_authed/bot/$botId": {
      id: "/_authed/bot/$botId"
      path: "/bot/$botId"
      fullPath: "/bot/$botId"
      preLoaderRoute: typeof AuthedBotBotIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    "/_authed/$workspaceSlug/bot/$botId": {
      id: "/_authed/$workspaceSlug/bot/$botId"
      path: "/bot/$botId"
      fullPath: "/$workspaceSlug/bot/$botId"
      preLoaderRoute: typeof AuthedWorkspaceSlugBotBotIdRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRouteRoute
    }
    "/_authed/$workspaceSlug/room/$roomId": {
      id: "/_authed/$workspaceSlug/room/$roomId"
      path: "/room/$roomId"
      fullPath: "/$workspaceSlug/room/$roomId"
      preLoaderRoute: typeof AuthedWorkspaceSlugRoomRoomIdRouteImport
      parentRoute: typeof AuthedWorkspaceSlugRouteRoute
    }
  }
}

interface AuthedWorkspaceSlugRouteRouteChildren {
  AuthedWorkspaceSlugBotBotIdRoute: typeof AuthedWorkspaceSlugBotBotIdRoute
  AuthedWorkspaceSlugRoomRoomIdRoute: typeof AuthedWorkspaceSlugRoomRoomIdRoute
}

const AuthedWorkspaceSlugRouteRouteChildren: AuthedWorkspaceSlugRouteRouteChildren =
  {
    AuthedWorkspaceSlugBotBotIdRoute: AuthedWorkspaceSlugBotBotIdRoute,
    AuthedWorkspaceSlugRoomRoomIdRoute: AuthedWorkspaceSlugRoomRoomIdRoute,
  }

const AuthedWorkspaceSlugRouteRouteWithChildren =
  AuthedWorkspaceSlugRouteRoute._addFileChildren(
    AuthedWorkspaceSlugRouteRouteChildren,
  )

interface AuthedRouteRouteChildren {
  AuthedWorkspaceSlugRouteRoute: typeof AuthedWorkspaceSlugRouteRouteWithChildren
  AuthedOnboardingRoute: typeof AuthedOnboardingRoute
  AuthedBotBotIdRoute: typeof AuthedBotBotIdRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedWorkspaceSlugRouteRoute: AuthedWorkspaceSlugRouteRouteWithChildren,
  AuthedOnboardingRoute: AuthedOnboardingRoute,
  AuthedBotBotIdRoute: AuthedBotBotIdRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  DesignRoute: DesignRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
